access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  application:
    name: PafBackend
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://akilahimaja:AZwgOd4L0VTNge50@chopchop.0vod3u4.mongodb.net/?retryWrites=true&ssl=true
      database: ${MONGODB_DB}

  #

logging:
  level:
    org.springframework.security: DEBUG
